# Generated by Django 4.2.7 on 2023-12-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogposts_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
