# Generated by Django 4.2.7 on 2023-12-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_author_id_blogpost_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='user_id',
        ),
    ]
