# Generated by Django 4.2.7 on 2023-12-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_author_blogpost_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
    ]
